apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-control-spring
  labels:
    app: live-control-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live-control-spring
  template:
    metadata:
      labels:
        app: live-control-spring
    spec:
      containers:
        - name: live-control-container # 컨테이너 이름, 자유롭게 설정 가능
          image: 615299753054.dkr.ecr.us-east-1.amazonaws.com/spring/jj-server:latest
          ports:
            - containerPort: 8888 # 애플리케이션이 사용하는 포트